site_name: "TechDocs"
site_description: "Custom documentation"

nav:
  - Introduction: index.md
  - Reusable Workflows:
    - State Repo Analyze Changes: state-repo-analyze-changes.md
    - State Repo Helm: state-repo-helm.md

plugins:
  - techdocs-core
