


FROM node:18-rev23-build AS builder


ARG API_URL="https://api-url"


WORKDIR /app
COPY . .

RUN npm ci && npm run build

FROM node:18-rev23-run


RUN apt-get update && apt-get install -y curl 


COPY --from=builder /app /app

WORKDIR /app
USER node
EXPOSE 3000
CMD ["npm", "start"]