on:
  push:
    branches:
      - main
name: Run Release Please
jobs:
  release-please:
    name: Release Please Manifest
    runs-on: ubuntu-latest
    steps:

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          config-file: release-please-config.json
          release-type: python
          manifest-file: .release-please-manifest.json
