name: Run Release Please

on:
  push:
    branches:
      - main
jobs:
  release-please:
    name: Release Please Manifest
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          release-type: python
