name: Run Release Please

on:
  push:
    branches:
      - main
jobs:
  release-please:
    name: Release Please Manifest
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          release-type: python

      - uses: actions/checkout@v4
        if: steps.release.outputs.tag_name != ''
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - name: Get major version num and update tag
        if: steps.release.outputs.tag_name != ''
        run: |
          git config --global user.name 'Prefapp Bot'
          git config --global user.email 'prefapp-bot@users.noreply.github.com'
          git tag -fa ${{ steps.release.outputs.major }} -m "Update major version tag"
          git push origin ${{ steps.release.outputs.major }} --force
