name: State repo helm
on:
  workflow_call:
    inputs:
      apply:
        required: true
        type: boolean
      environment:
        required: true
        type: string
      # JSON file
      updated_apps:
        required: true
        type: string
      config_file:
        required: true
        type: string
      sops_enabled:
        required: false
        default: false
        type: boolean
      # Versions inputs
      version_kubectl:
        type: string
        required: false
        default: '1.28.8'
      version_kubectl_release_date:
        type: string
        required: false
        default: '2024-04-19'
      version_kustomize:
        type: string
        required: false
        default: '5.4.2'
      version_helm:
        type: string
        required: false
        default: 'v3.14.0'
      version_helmfile:
        type: string
        required: false
        default: 'v0.161.0'
      version_helm_diff_plugin:
        type: string
        required: false
        default: 'v3.9.9'
      version_secrets:
        type: string
        required: false
        default: 'v4.4.2'
      version_sops:
        type: string
        required: false
        default: 'v3.7.1'
jobs:
  helm:
    runs-on: ubuntu-22.04
    env:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install js-yaml
      - name: Parse config file
        id: parse_config
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const path = require("path");
            const yaml = require('js-yaml');

            const configPath = path.join("${{ github.workspace }}", "${{ inputs.config_file }}");

            console.log(configPath);

            const config = yaml.load(fs.readFileSync(configPath, 'utf8'));

            const provider = config.provider;
            const helm_registries = config.helm_registries

            const { cluster_name, identifier } = config.environments["${{ inputs.environment }}"];

            const result = {
              provider_kind: provider.kind,
              cluster_name,
              identifier,
              helm_registries,
            }

            switch(provider.kind) {
              case 'azure':
                if(!provider?.tenant_id) throw new Error('AZURE_TENANT_ID not configured')
                if(!provider?.subscription_id) throw new Error('AZURE_SUBSCRIPTION_ID not configured')
                
                result.tenant_id = provider.tenant_id
                result.subscription_id = provider.subscription_id
                result.resource_group_name = config.environments["${{ inputs.environment }}"].resource_group_name
                
                break;
              default:
                throw new Error(`Unknown provider: ${providerKind}`)
            }


            console.log(result);

            return result;

      # Azure setup

      - name: debug
        run: |
          echo "${{ fromJSON(steps.parse_config.outputs.result).identifier }}"
          echo "${{ fromJSON(steps.parse_config.outputs.result).tenant_id }}"
          echo "${{ fromJSON(steps.parse_config.outputs.result).subscription_id }}"
      - name: Setup / Azure Login
        uses: Azure/login@v2
        if: ${{ steps.parse_config.outputs.result.provider_kind }} == "azure"
        with:
          client-id: ${{ steps.parse_config.outputs.result && fromJSON(steps.parse_config.outputs.result).identifier }}
          tenant-id: ${{ steps.parse_config.outputs.result && fromJSON(steps.parse_config.outputs.result).tenant_id }}
          subscription-id: ${{ steps.parse_config.outputs.result && fromJSON(steps.parse_config.outputs.result).subscription_id }}

      - name: Set up kubelogin for non-interactive login
        if: ${{ steps.parse_config.outputs.result.provider_kind }} == "azure"
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.24'

      - name: Setup / AKS Context
        if: ${{ steps.parse_config.outputs.result.provider_kind }} == "azure"
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ steps.parse_config.outputs.result && fromJSON(steps.parse_config.outputs.result).resource_group_name }}
          cluster-name: ${{ steps.parse_config.outputs.result && fromJSON(steps.parse_config.outputs.result).cluster_name }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Login to ACRs
        if:  ${{ steps.parse_config.outputs.result.provider_kind }} == "azure"
        run: |
          registries='${{ toJSON(fromJSON(steps.parse_config.outputs.result).helm_registries) }}'

          echo "$registries" | jq -r '.[]' | while read registry; do
            echo "Login in $registry"
            token=$(az acr login --name $registry --expose-token --output tsv --query accessToken) && \
            echo $token | helm registry login $registry -u 00000000-0000-0000-0000-000000000000 --password-stdin
          done

      # Helm logic
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v2.0.0
        with:
          kubectl-version: '${{ inputs.version_kubectl }}'
          kubectl-release-date: '${{ inputs.version_kubectl_release_date }}'
          helmfile-version: '${{ inputs.version_helmfile }}' 
          helm-version: '${{ inputs.version_helm }}'
          helm-diff-plugin-version: '${{ inputs.version_helm_diff_plugin}}'

      - uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '${{ inputs.version_kustomize }}'

      - name: Setup / SOPS
        env:
          SOPS_VERSION: '${{ inputs.version_sops }}'
          HELM_SECRETS_VERSION: '${{ inputs.version_secrets }}'
        if: ${{ inputs.sops_enabled == true || inputs.sops_enabled == 'true' }}
        run: |
          
          curl -O -L -C - "https://github.com/mozilla/sops/releases/download/$SOPS_VERSION/sops-$SOPS_VERSION.linux"
          sudo mv "sops-$SOPS_VERSION.linux" /usr/bin/sops
          sudo chmod +x /usr/bin/sops
          
          helm plugin install --debug https://github.com/jkroepke/helm-secrets

      - name: Helm diff
        if: ${{ inputs.apply == false || inputs.apply == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DIFF_FILE="/tmp/helmfile.md"

          cd ${{ github.workspace }}/sys_services

          apps='${{ inputs.updated_apps }}'

          echo $apps

          echo "$apps" | jq -r '.[]' | while read app; do

            helmfile --environment ${{ inputs.environment }} template > /tmp/manifests.yml

            if [ -z /tmp/manifests.yml ]; then
              kubectl apply -f /tmp/manifests.yml --dry-run=server
              rm /tmp/manifests.yml
            else
              echo "::warning app=$app,env=${{inputs.environment}}::The helm deploy did not generate any manifest."
            fi

            # Verify the app exists or if it is the first time it's been applied
            appname=$(echo $app | awk -F"/" '{print $NF}')

            releases_found=`helm list -A -o json | jq "map(select(.name == \"$appname\" )) | length"`
            
            if [ $releases_found -gt 0 ]; then
              diff_output=`helmfile --environment ${{ inputs.environment }} --selector release=$appname diff --detailed-exitcode --context 5 | grep --color=never "\S"`
              cat <<EOF >> $DIFF_FILE
          <details>
          <summary><h2> Helm diff in app: $appname, env: ${{ inputs.environment }}</h2></summary>

            \`\`\`diff
            $(echo "$diff_output" | sed 's/^/  /')
            \`\`\`
          EOF
              gh pr comment ${{ github.event.number }} -F $DIFF_FILE
            else
              echo 'Installing for the first time'
            fi

          done
      
      - name: Helm apply
        if: ${{ inputs.apply == true || inputs.apply == 'true' }}
        run: |

          apps='${{ inputs.updated_apps }}'
          
          cd ${{ github.workspace }}/sys_services
          
          echo $apps

          echo "$apps" | jq -r '.[]' | while read app; do

            appname=$(echo $app | awk -F"/" '{print $NF}')
            helmfile --environment ${{ inputs.environment }}  --selector release=$appname apply

          done
