name: State repo analyze changes
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      gh_app_id:
        required: true
        type: string
    secrets:
      gh_pem_file:
        required: true
    outputs:
      changes:
        description: "The first output string"
        value: ${{ jobs.analyze_changes.outputs.changes }}
jobs:
  analyze_changes:
    runs-on: ubuntu-24.04
    outputs:
      changes: ${{ steps.analyze_changes.outputs.result }}
    steps:
      - name: Get Token from Github App
        id: get-gh-app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ inputs.gh_app_id }}
          private-key: ${{ secrets.gh_pem_file }}
          owner: ${{ github.repository_owner }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Calculate changes
        id: calculate_changes
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            changed:
              - added|modified: '${{ inputs.path }}/**/*.yaml'
              - added|modified: '${{ inputs.path }}/**/*.yml'
      - name: Analyze files changed
        id: analyze_changes
        uses: actions/github-script@v7
        with:
          script: |
            const path = require("path");
            const fs = require("fs");

            const changedFiles = JSON.parse(${{ toJson(steps.calculate_changes.outputs.changed_files) }});
            
            const ignoredDirectories = [".github", ".docs"];
            const ignoredFiles = ["helmfile.yaml"];

            const changedDeployments = new Set();

            changedFiles.forEach( f => {

              const pathComponents = path.normalize(f).split(path.sep)

              console.log(f);

              if(ignoredDirectories.includes(pathComponents[0])) return;
              if(ignoredFiles.includes(pathComponents.at(-1))) return;

              const type = f.shift()

              let cluster, tenant, app, env, file;
              if (type === "apps") {
                [type, cluster, tenant, app, env, file] = pathComponents;
                changedDeployments.add([type, cluster, tenant, app, env].join("/"));
              } else if(type === "sys_apps") {
                [type, cluster, app, file] = pathComponents;
                changedDeployments.add([type, cluster, app].join("/"));
              }

            });

            console.debug(changedDeployments);

            const result = Array.from(changedDeployments);

            console.debug(result);

            return result;
